- name: Copy docker-compose file
  copy:
    src: ../files
    dest: /var/provotum

- name: Creating .env file
  copy:
    dest: "/var/provotum/files/.env"
    content: |
      IDENTITY_PROVIDER_URL={{identity_provider_url}}
      IDENTITY_PROVIDER_IMAGE={{identity_provider_image}}
      VOTING_AUTHORITY_URL={{voting_authority_url}}
      VOTING_AUTHORITY_IMAGE={{voting_authority_image}}
      CHAIN_URL={{chain_url}}
      CHAIN_WS_URL={{chain_ws_url}}
      SEALER_BOB_FRONTEND_URL={{sealer_bob_frontend_url}}
      SEALER_BOB_FRONTEND_IMAGE={{sealer_bob_frontend_image}}
      SEALER_CHARLIE_FRONTEND_URL={{sealer_charlie_frontend_url}}
      SEALER_CHARLIE_FRONTEND_IMAGE={{sealer_charlie_frontend_image}}
      SEALER_BOB_URL={{sealer_bob_url}}
      SEALER_CHARLIE_URL={{sealer_charlie_url}}
      SEALER_IMAGE={{sealer_image}}

- name: Docker Login
  become: true
  shell:
    cmd: "docker login {{docker_registry}} -u {{docker_registry_username}} -p {{docker_registry_password}}"

- name: Run Server
  become: true
  shell:
    chdir: /var/provotum/files
    cmd: "docker-compose up -d"
