- name: Restart Provotum
  become: true
  shell:
    chdir: /var/provotum/files
    cmd: docker-compose restart

- name: Start Chain
  shell: curl -X POST https://{{voting_authority_url}}/bootstrap/chain?restart=false

- name: Get Chain Specs Bob
  shell: curl -X POST https://{{sealer_bob_url}}/bootstrap/chain-spec

- name: Get Chain Specs Charlie
  shell: curl -X POST https://{{sealer_charlie_url}}/bootstrap/chain-spec

- name: Pause
  pause:
    seconds: 5

- name: Start Chain Node Bob
  shell: curl -X POST https://{{sealer_bob_url}}/bootstrap/chain/bootnode?restart=false

- name: Start Chain Node Charlie
  shell: curl -X POST https://{{sealer_charlie_url}}/bootstrap/chain/bootnode?restart=false

- name: Pause
  pause:
    seconds: 5

- name: Insert validator keys Bob
  shell: curl -X POST https://{{sealer_bob_url}}/bootstrap/validators

- name: Insert validator keys Charlie
  shell: curl -X POST https://{{sealer_charlie_url}}/bootstrap/validators
