- name: Install jq
  apt: name=jq state=latest update_cache=yes

- name: Copy customSpecDefault.json to customSpec.json
  become: true
  local_action: shell cp ./roles/provotum-v3-mn-server-inst/files/customSpecDefault.json ./roles/provotum-v3-mn-server-inst/files/customSpec.json

- name: Copy docker-compose file
  copy:
    src: ../files/docker-compose.yml
    dest: ./

- name: Creating .env file
  copy:
    dest: "./.env"
    content: |
      NODE_IMAGE={{node_image}}
      RANDOMIZER_IMAGE={{randomizer_image}}

- name: Docker Login
  become: true
  shell:
    cmd: "docker login {{docker_registry}} -u {{docker_registry_username}} -p {{docker_registry_password}}"

- name: Get aura key
  command: "awk 'NR == 2 {print $1}' RS='SS58 Address:      ' FS='\n' ./aura"
  register: auraPublicKey

- name: Add aura key to balances
  become: true
  local_action: shell echo "$( jq ".genesis.runtime.palletBalances.balances[.genesis.runtime.palletBalances.balances | length] |= . +  [\"{{auraPublicKey.stdout}}\", 1152921504606846976]" "./roles/provotum-v3-mn-server-inst/files/customSpec.json" )" > ./roles/provotum-v3-mn-server-inst/files/customSpec.json

- name: Add aura key to voting authority
  become: true
  local_action: shell echo "$( jq ".genesis.runtime.palletMixnet.votingAuthorities[.genesis.runtime.palletMixnet.votingAuthorities | length] |= . + \"{{auraPublicKey.stdout}}\""  "./roles/provotum-v3-mn-server-inst/files/customSpec.json" )" > ./roles/provotum-v3-mn-server-inst/files/customSpec.json
