version: "3.7"

services:
  clair_postgres:
    image: postgres:12.1
    restart: unless-stopped
    volumes:
      - ./clair/postgres:/var/lib/postgresql/data:rw
    environment:
      - POSTGRES_USER=${CLAIR_DB_USER}
      - POSTGRES_PASSWORD=${CLAIR_DB_PASSWORD}
      - POSTGRES_DB=clair

  clair:
    image: quay.io/coreos/clair:v4.0.1
    restart: unless-stopped
    volumes:
      - ./clair/config:/config/:ro
      - ./clair/clair-tmp:/tmp/:rw
    depends_on:
      clair_postgres:
        condition: service_started
    command: [-conf=/config/config.yml, -mode=combo]


networks:
  default:
    external:
      name: files_provotum-quay
