version: "3.9"
services:
  quay:
    container_name: quay
    image: quay.io/projectquay/quay:latest
    privileged: true
    volumes:
      - ./quay/config:/conf/stack:Z
      - ./quay/storage:/datastorage:Z
    labels:
      - "traefik.docker.network=files_provotum-quay"
      - "traefik.enable=true"
      - "traefik.basic.frontend.rule=Host:${VIRTUAL_HOST}"
      - "traefik.basic.port=8080"
      - "traefik.basic.protocol=http"

networks:
  default:
    external:
      name: files_provotum-quay
