version: "3.9"
services:
  quay:
    container_name: quay
    image: quay.io/projectquay/quay:latest
    privileged: true
    volumes:
      - ./quay/config:/conf/stack:Z
      - ./quay/storage:/datastorage:Z
    environment:
      - VIRTUAL_HOST=${VIRTUAL_HOST}
      - LETSENCRYPT_HOST=${LETSENCRYPT_HOST}
      - VIRTUAL_PORT=8080

networks:
  default:
    external:
      name: files_provotum-quay
