version: "3.9"
services:
  quay:
    image: quay.io/projectquay/quay:latest
    privileged: true
    ports:
      - 8081:8080
    volumes:
      - ./quay/config:/conf/stack:Z
      - ./quay/storage:/datastorage:Z

networks:
  default:
    external:
      name: files_provotum-quay
