---

- name: Copy docker-compose files
  copy:
    src: ../files
    dest: /var/jenkins

- name: Creating .env file
  copy:
    dest: "/var/jenkins/files/.env"
    content: |
      VIRTUAL_HOST={{ hostname }}
      LETSENCRYPT_HOST={{ hostname }}

- name: Run jenkins
  become: true
  shell:
    chdir: /var/jenkins/files
    cmd: "docker-compose up -d"

- name: Wait for jenkins admin file exists
  become: true
  shell:
    cmd: "docker exec jenkins bash -c 'while ! test -f /var/jenkins_home/secrets/initialAdminPassword; do sleep 2; done'"

- name: print to inital admin password
  command: docker exec jenkins cat /var/jenkins_home/secrets/initialAdminPassword
  register: initialAdminPassword

- debug: msg="Initial Admin Password for Jenkins {{ initialAdminPassword.stdout }}"
