- name: Copy docker-compose file
  copy:
    src: ../files
    dest: /var/provotum

- name: Creating .env file
  copy:
    dest: "/var/provotum/files/.env"
    content: |
      IDENTITY_PROVIDER_URL={{identity_provider_url}}
      IDENTITY_PROVIDER_IMAGE={{identity_provider_image}}
      RANDOMIZER_URL={{randomizer_url}}
      RANDOMIZER_IMAGE={{randomizer_image}}
      VOTING_AUTHORITY_URL={{voting_authority_url}}
      VOTING_AUTHORITY_IMAGE={{voting_authority_image}}
      FRONTEND_URL={{frontend_url}}
      FRONTEND_IMAGE={{frontend_image}}
      CHAIN_URL={{chain_url}}
      CHAIN_WS_URL={{chain_ws_url}}
      SEALER_1_URL={{sealer_1_url}}
      SEALER_2_URL={{sealer_2_url}}
      SEALER_IMAGE={{sealer_image}}

- name: Docker Login
  become: true
  shell:
    cmd: "docker login {{docker_registry}} -u {{docker_registry_username}} -p {{docker_registry_password}}"

- name: Run Server
  become: true
  shell:
    chdir: /var/provotum/files
    cmd: "docker-compose up -d"
