- name: Install required system packages
  apt: name=acl state=latest update_cache=yes

- name: Copy docker-compose files
  copy:
    src: ../files
    dest: /var/quay

- name: Creating .env file
  copy:
    dest: "/var/quay/files/.env"
    content: |
      QUAY_DB_USER={{ quay_db_user }}
      QUAY_DB_PASSWORD={{ quay_db_password }}
      REDIS_PASSWORD={{ quay_redis_password }}
      VIRTUAL_HOST={{ hostname }}
      LETSENCRYPT_HOST={{ hostname }}

- name: Run DB and Redis
  become: true
  shell:
    chdir: /var/quay/files
    cmd: "docker-compose -f docker-compose-storage.yml up -d"

- name: Wait for running db
  become: true
  shell:
    chdir: /var/quay/files
    cmd: "docker exec -it quay-db bash -c 'while ! pg_isready; do sleep 2; done'"

- name: Enable pg_trgm for DB
  become: true
  shell: docker exec -it quay-db /bin/bash -c 'echo "CREATE EXTENSION IF NOT EXISTS pg_trgm" | psql -d quay -U {{ quay_db_user }}'

- name: Insert quay config
  blockinfile:
    path: /var/quay/files/quay/config/config.yaml
    block: |
      BUILDLOGS_REDIS.host: redis
      BUILDLOGS_REDIS.password: {{ quay_redis_password }}
      BUILDLOGS_REDIS.port: 6379
      CONTACT_INFO: {{ contact_info }}
      DB_URI: postgresql://{{ quay_db_user }}:{{ quay_db_password }}@quay-db/quay
      ENTERPRISE_LOGO_URL: {{ enterprise_logo_url }}
      REGISTRY_TITLE: {{ registry_title }}
      REGISTRY_TITLE_SHORT: {{ registry_title }}
      SERVER_HOSTNAME: {{ hostname }}
      USER_EVENTS_REDIS.host: redis
      USER_EVENTS_REDIS.password: {{ quay_redis_password }}
      USER_EVENTS_REDIS.port: 6379


- name: Create directory for images
  file:
    path: /var/quay/files/quay/storage
    state: directory

- name: Set rights for storage directory
  shell:
    chdir: /var/quay/files/quay
    cmd: "setfacl -m u:1001:-wx storage"

- name: Run quay
  become: true
  shell:
    chdir: /var/quay/files
    cmd: "docker-compose -f docker-compose-quay.yml up -d"
