- name: Install required system packages
  apt: name=acl state=latest update_cache=yes

- name: Copy docker-compose files
  copy:
    src: ../files
    dest: /var/quay

- name: Creating .env file
  copy:
    dest: "/var/quay/files/.env"
    content: |
      DB_USER={{ db_user }}
      DB_PASSWORD={{ db_password }}
      REDIS_PASSWORD={{ redis_password }}

- name: Run DB and Redis
  become: true
  shell:
    chdir: /var/quay/files
    cmd: "docker-compose -f docker-compose-storage.yml up -d"

- name: Enable pg_trgm for DB
  become: true
  shell: docker exec -it files_postgres_1 /bin/bash -c 'echo "CREATE EXTENSION IF NOT EXISTS pg_trgm" | psql -d quay -U {{ db_user }}'

- name: Insert quay config
  blockinfile:
    path: /var/quay/files/config/config.yaml
    block: |
      BUILDLOGS_REDIS.host: redis
      BUILDLOGS_REDIS.password: {{ redis_password }}
      BUILDLOGS_REDIS.port: 6379
      CONTACT_INFO: {{ contact_info }}
      DB_URI: postgresql://{{ db_user }}:{{ db_password }}@postgres/quay
      ENTERPRISE_LOGO_URL: {{ enterprise_logo_url }}
      REGISTRY_TITLE: {{ registry_title }}
      REGISTRY_TITLE_SHORT: {{ registry_title }}
      SERVER_HOSTNAME: {{ inventory_hostname }}:8081
      USER_EVENTS_REDIS.host: redis
      USER_EVENTS_REDIS.password: {{ redis_password }}
      USER_EVENTS_REDIS.port: 6379

- name: Create directory for images
  file:
    path: /var/quay/files/storage
    state: directory

- name: Set rights for storage directory
  shell:
    chdir: /var/quay/files
    cmd: "setfacl -m u:1001:-wx storage"

- name: Run quay
  become: true
  shell:
    chdir: /var/quay/files
    cmd: "docker-compose -f docker-compose-quay.yml up -d"
