version: "3.8"

services:
  va:
    container_name: va
    image: ${NODE_IMAGE}
    command: --chain=./customSpec.json --name va --base-path /tmp/va --port 30333 --ws-port 9944 --rpc-port 9933 --ws-external --rpc-external --rpc-cors all --execution Native
    ports:
      - 9933:9933
    labels:
      - "traefik.docker.network=files_provotum-server"
      - "traefik.enable=true"
      - "traefik.chain.frontend.rule=Host:${CHAIN_VA_URL}"
      - "traefik.chain.port=30333"
      - "traefik.chain.protocol=http"
      - "traefik.chainws.frontend.rule=Host:${CHAIN_VA_WS_URL}"
      - "traefik.chainws.port=9944"
      - "traefik.chainws.protocol=http"
    volumes:
      - ./customSpec.json:/provotum/customSpec.json

  randomizer:
    container_name: randomizer
    image: ${RANDOMIZER_IMAGE}

  client:
    container_name: client
    image: ${CLIENT_IMAGE}
    environment:
      - "VA_URL=${VA_URL}"
      - "VA_MNEMONIC=${VA_MNEMONIC}"
      - "RANDOMIZER_URL=${RANDOMIZER_URL}"
      - "BATCH_SIZE=${BATCH_SIZE}"

networks:
  default:
    external: true
    name: provotum-server
