version: "3.8"

services:
  # Alice is the Voting Authority
  # Alice doesn't validate any blocks -> just runs a full node
  va:
    container_name: va
    image: ${NODE_IMAGE}
    command: --chain=./customSpec.json --name va --base-path /tmp/va --port 30333 --ws-port 9944 --rpc-port 9933 --execution Native
    network_mode: host
    volumes:
      - ./customSpec.json:/provotum/customSpec.json

  # Randomizer is a simple web service to re-encrypt the voter's ballots
  randomizer:
    container_name: randomizer
    image: ${RANDOMIZER_IMAGE}
    network_mode: host
