version: "3.8"

services:
  # Alice is the Voting Authority
  # Alice doesn't validate any blocks -> just runs a full node
  va:
    container_name: va
    image: ${NODE_IMAGE}
    command: --chain=./customSpec.json --name va --base-path /tmp/va --port 30333 --ws-port 9944 --rpc-port 9933 --ws-external --rpc-external --rpc-cors all --execution Native
    ports:
      - 30333:30333
      - 9933:9933
      - 9944:9944
    volumes:
      - ./customSpec.json:/provotum/customSpec.json

  # Randomizer is a simple web service to re-encrypt the voter's ballots
  randomizer:
    container_name: randomizer
    image: ${RANDOMIZER_IMAGE}
    ports:
      - 8080:8080

  client:
    container_name: client
    image: ${CLIENT_IMAGE}
    environment:
      - "VA_URL=${VA_URL}"
      - "VA_MNEMONIC=${VA_MNEMONIC}"
      - "RANDOMIZER_URL=${RANDOMIZER_URL}"
