version: "3.9"
services:

  jenkins:
    container_name: jenkins
    build: .
    networks:
      - "provotum-jenkins"
    labels:
      - "traefik.docker.network=files_provotum-jenkins"
      - "traefik.enable=true"
      - "traefik.basic.frontend.rule=Host:${VIRTUAL_HOST}"
      - "traefik.basic.port=8080"
      - "traefik.basic.protocol=http"
    volumes:
      - "/var/jenkins/files/data:/var/jenkins_home"
      - "/var/run/docker.sock:/var/run/docker.sock"
    restart: always

networks:
  provotum-jenkins:
