version: "3.9"
services:

  jenkins:
    container_name: jenkins
    build: .
    networks:
      - "provotum-jenkins"
    environment:
      - VIRTUAL_HOST=${VIRTUAL_HOST}
      - LETSENCRYPT_HOST=${LETSENCRYPT_HOST}
      - VIRTUAL_PORT=8080
    volumes:
      - "/var/jenkins/files/data:/var/jenkins_home"
      - "/var/run/docker.sock:/var/run/docker.sock"
    restart: always

networks:
  provotum-jenkins:
