---

application_name: quay

db_user: user
db_password: password
redis_password: password

contact_info: http://provotum.ch/
enterprise_logo_url: http://provotum.ch/pv-logo-light-diamond.svg
registry_title: Provotum
