---
version: '2.3'

services:

  influxdb:
    container_name: influxdb
    image: influxdb:1.4
    environment:
      INFLUXDB_ADMIN_USER: ${INFLUXDB_USERNAME}
      INFLUXDB_ADMIN_PASSWORD: ${INFLUXDB_PASSWORD}
      INFLUXDB_DB: ${INFLUXDB_DATABASE}
    volumes:
      - ./config/influxdb/influxdb.conf:/etc/influxdb/influxdb.conf
      - ./influxdb-data:/var/lib/influxdb
    labels:
      - "traefik.docker.network=files_sys-log"
      - "traefik.enable=true"
      - "traefik.basic.frontend.rule=Host:${INFLUX_VIRTUAL_HOST}"
      - "traefik.basic.port=8086"
      - "traefik.basic.protocol=http"
    networks:
      - "sys-log"

  grafana:
    container_name: grafana
    image: grafana/grafana:6.0.2
    user: "root"
    environment:
      GF_SECURITY_ADMIN_USER: ${GF_SECURITY_ADMIN_USER}
      GF_SECURITY_ADMIN_PASSWORD: ${GF_SECURITY_ADMIN_PASSWORD}
    volumes:
      - ./config/grafana/datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml
      - ./config/grafana/dashboard.yaml:/etc/grafana/provisioning/dashboards/dashboard.yaml
      - ./config/grafana/DashboardTelegraf.json:/var/lib/grafana/dashboards/DashboardTelegraf.json
      - ./grafana-data:/var/lib/grafana
    labels:
      - "traefik.docker.network=files_sys-log"
      - "traefik.enable=true"
      - "traefik.basic.frontend.rule=Host:${GRAFANA_VIRTUAL_HOST}"
      - "traefik.basic.port=3000"
      - "traefik.basic.protocol=http"
    networks:
      - "sys-log"

networks:
  sys-log:
