---

- name: Install docker-compose
  get_url:
      url : https://github.com/docker/compose/releases/download/1.28.4/docker-compose-Linux-x86_64
      dest: /usr/local/bin/docker-compose
      mode: 'u+x,g+x'

- name: Set rights
  become: true
  file:
    path: /usr/local/bin/docker-compose
    mode: '+x'
