- name: Create aura.json and grandpa.json
  become: true
  shell: |
    cp key.json aura.json
    cp key.json grandpa.json
    echo "$( jq ".params[.params | length] |= . +  \"aura\"" "./aura.json" )" > ./aura.json
    echo "$( jq ".params[.params | length] |= . +  \"$(awk 'NR == 2 {print $1}' RS='`' FS='`' ./aura)\"" "./aura.json" )" > ./aura.json
    echo "$( jq ".params[.params | length] |= . +  \"$(awk 'NR == 2 {print $1}' RS='Public key \\(hex\\):  ' FS='\n' ./aura)\"" "./aura.json" )" > ./aura.json
    echo "$( jq ".params[.params | length] |= . +  \"gran\"" "./grandpa.json" )" > ./grandpa.json
    echo "$( jq ".params[.params | length] |= . +  \"$(awk 'NR == 2 {print $1}' RS='`' FS='`' ./grandpa)\"" "./grandpa.json" )" > ./grandpa.json
    echo "$( jq ".params[.params | length] |= . +  \"$(awk 'NR == 2 {print $1}' RS='Public key \\(hex\\):  ' FS='\n' ./grandpa)\"" "./grandpa.json" )" > ./grandpa.json

- name: Copy customSpec.json
  copy:
    src: ../../provotum-v3-mn-server-inst/files/customSpec.json
    dest: ./

- name: Run Server
  become: true
  shell:
    cmd: "docker-compose up -d"

- pause:
    seconds: 20

- name: Get id
  shell: "docker logs va 2>&1 | awk 'NR == 2 {print $1}' RS='Local node identity is: ' FS=' '"
  args:
    executable: /bin/bash
  register: id

- name: Remove bootnode line from sealer main.yml
  become: true
  local_action: shell sed '/bootnode/d' ./roles/provotum-v3-mn-sealer-start/defaults/main.yml > ./roles/provotum-v3-mn-sealer-start/defaults/main-temp.yml; mv ./roles/provotum-v3-mn-sealer-start/defaults/main-temp.yml ./roles/provotum-v3-mn-sealer-start/defaults/main.yml

- name: Add bootnode
  become: true
  local_action: "shell echo \"bootnode: /dns/va.{{inventory_hostname}}/tcp/443/p2p/{{id.stdout}}\" >> ./roles/provotum-v3-mn-sealer-start/defaults/main.yml"

- name: Add aura key to keystore
  shell: curl http://localhost:9933 -H "Content-Type:application/json;charset=utf-8" -d "@./aura.json"

- name: Add grandpa key to keystore
  shell: curl http://localhost:9933 -H "Content-Type:application/json;charset=utf-8" -d "@./grandpa.json"

- name: Remove key.json
  file:
    path: key.json
    state: absent

- name: Remove aura.json
  file:
    path: aura.json
    state: absent

- name: Remove aura
  file:
    path: aura
    state: absent

- name: Remove grandpa.json
  file:
    path: grandpa.json
    state: absent

- name: Remove grandpa
  file:
    path: grandpa
    state: absent
