- name: Create aura.json and grandpa.json
  become: true
  shell: |
    cp key.json aura.json
    cp key.json grandpa.json
    echo "$( jq ".params[.params | length] |= . +  \"aura\"" "./aura.json" )" > ./aura.json
    echo "$( jq ".params[.params | length] |= . +  \"$(awk 'NR == 2 {print $1}' RS='`' FS='`' ./aura)\"" "./aura.json" )" > ./aura.json
    echo "$( jq ".params[.params | length] |= . +  \"$(awk 'NR == 2 {print $1}' RS='Public key \\(hex\\):  ' FS='\n' ./aura)\"" "./aura.json" )" > ./aura.json
    echo "$( jq ".params[.params | length] |= . +  \"gran\"" "./grandpa.json" )" > ./grandpa.json
    echo "$( jq ".params[.params | length] |= . +  \"$(awk 'NR == 2 {print $1}' RS='`' FS='`' ./grandpa)\"" "./grandpa.json" )" > ./grandpa.json
    echo "$( jq ".params[.params | length] |= . +  \"$(awk 'NR == 2 {print $1}' RS='Public key \\(hex\\):  ' FS='\n' ./grandpa)\"" "./grandpa.json" )" > ./grandpa.json

- name: Copy customSpec.json
  copy:
    src: ../../provotum-v3-mn-server-inst/files/customSpec.json
    dest: ./

- name: Run Server
  become: true
  shell:
    cmd: "docker-compose up -d"

- pause:
    seconds: 20

- name: Get id
  shell: "docker logs va 2>&1 | awk 'NR == 2 {print $1}' RS='Local node identity is: ' FS=' '"
  args:
    executable: /bin/bash
  register: id

- debug: msg="Bootstrap url /ip4/{{ansible_default_ipv4.address}}/tcp/30333/p2p/{{id.stdout}}"

- name: Add aura key to keystore
  shell: curl http://localhost:9933 -H "Content-Type:application/json;charset=utf-8" -d "@./aura.json"

- name: Add grandpa key to keystore
  shell: curl http://localhost:9933 -H "Content-Type:application/json;charset=utf-8" -d "@./grandpa.json"
