version: '3.8'

services:
  sealer:
    image: ${SEALER_IMAGE}
    environment:
      - KEY=//Sealer${SEALER_NUMBER}
      - DKG_KEY=sealer${SEALER_NUMBER}
      - NAME=sealer-${SEALER_NUMBER}
      - DEBUG=client,binary
      - VOTING_AUTHORITY_URL=https://${VOTING_AUTHORITY_URL}
      - MONGODB_URI=mongodb://${MONGO_DB_URL}
      - MONGODB_NAME=sealer-${SEALER_NUMBER}
      - SUBSTRATE_HOST=${SUBSTRATE_HOST}
      - SUBSTRATE_WS_PORT=443
    labels:
      - "traefik.docker.network=files_provotum-sealer"
      - "traefik.enable=true"
      - "traefik.basic.frontend.rule=Host:${SEALER_URL}"
      - "traefik.basic.port=4000"
      - "traefik.basic.protocol=http"
    restart: always
    networks:
      - "provotum-sealer"

networks:
  provotum-sealer:
