version: '2'

services:
  traefik:
    image: traefik:v1.7
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/proxy/files/config/traefik.toml:/traefik.toml
      - /var/proxy/files/config/acme.json:/acme.json
    container_name: traefik

networks:
  default:
    external:
      name: ${NETWORK}
