http_listen_addr: :6060
introspection_addr: :8089
log_level: debug
indexer:
  connstring:
  scanlock_retry: 10
  layer_scan_concurrency: 5
  migrations: true
matcher:
  connstring:
  max_conn_pool: 100
  run: ""
  migrations: true
  indexer_addr: clair-indexer
notifier:
  connstring:
  delivery_interval: 1m
  poll_interval: 5m
  migrations: true
auth:
  psk:
    key: "ZGVjNmk4MWVkN2Y5Yw=="
    iss: ["quay"]
# tracing and metrics
trace:
  name: "jaeger"
  probability: 1
  jaeger:
    agent_endpoint: "localhost:6831"
    service_name: "clair"
metrics:
  name: "prometheus"
