---

- name: Set up all server applications for Provotum 3.0 MN
  hosts: all
  become: yes
  vars:
    - update_apt_cache: yes

  roles:
    - docker
    - docker-compose
    - subkey
    - provotum-v3-mn-server-inst
    - telegraf-inst
