---

- name: Set up all server applications for Provotum 3.0
  hosts: all
  become: yes
  vars:
    - update_apt_cache: yes

  roles:
    - docker
    - docker-compose
    - provotum-server-inst
    - role: reverse-proxy
      vars:
        network: files_provotum-server
