---

- name: Set up a sealer applications for Provotum 3.0 MN
  hosts: all
  become: yes
  vars:
    - update_apt_cache: yes

  roles:
    - docker
    - docker-compose
    - subkey
    - provotum-v3-mn-sealer-inst
    - role: reverse-proxy
      vars:
        network: provotum-server
    - telegraf-inst
