---

- name: Set up a central server for Provotum v3 with GUIs from Claudio
  hosts: all
  become: yes
  vars:
    - update_apt_cache: yes

  roles:
    - docker
    - docker-compose
    - provotum-v3-claudio-inst
    - role: reverse-proxy
      vars:
        network: files_provotum-server
