---

- name: Set up provotum v2 server
  hosts: all
  become: yes
  vars:
    - update_apt_cache: yes

  roles:
    - docker
    - docker-compose
    - provotum-v2-server-inst
    - role: reverse-proxy
      vars:
        network: e-voting
