---

- name: Set up a Project Quay Docker image registry server
  hosts: all
  become: yes
  vars:
    - update_apt_cache: yes

  roles:
    - docker
    - docker-compose
    - quay-inst
    - clair-inst
    - role: reverse-proxy
      vars:
        network: files_provotum-quay
