---

- name: Set up a System Log with InfluxDB, Grafana and Telegraf
  hosts: all
  become: yes
  vars:
    - update_apt_cache: yes

  roles:
    - docker
    - docker-compose
    - sys-log-inst
    - role: reverse-proxy
      vars:
        network: files_sys-log
