version: '3.8'

services:
  mongodb:
    image: mongo:4.2-bionic
    ports:
      - 27017:27017
    volumes:
      - ./data:/data
    networks:
      - "provotum-server"
    restart: always
  identity:
    image: ${IDENTITY_PROVIDER_IMAGE}
    environment:
      - VOTING_AUTHORITY_URL=http://va:4000
    labels:
      - "traefik.docker.network=files_provotum-server"
      - "traefik.enable=true"
      - "traefik.basic.frontend.rule=Host:${IDENTITY_PROVIDER_URL}"
      - "traefik.basic.port=4000"
      - "traefik.basic.protocol=http"
    networks:
      - "provotum-server"
    restart: always
  randomizer:
    image: ${RANDOMIZER_IMAGE}
    labels:
      - "traefik.docker.network=files_provotum-server"
      - "traefik.enable=true"
      - "traefik.basic.frontend.rule=Host:${RANDOMIZER_URL}"
      - "traefik.basic.port=4000"
      - "traefik.basic.protocol=http"
    networks:
      - "provotum-server"
    restart: always
  va:
    image: ${VOTING_AUTHORITY_IMAGE}
    environment:
      - KEY=//Voting-Authority
      - NAME=voting-authority
      - DEBUG=binary,client
      - MONGODB_URI=mongodb://mongodb:27017
      - MONGODB_NAME=voting-authority
    labels:
      - "traefik.docker.network=files_provotum-server"
      - "traefik.enable=true"
      - "traefik.basic.frontend.rule=Host:${VOTING_AUTHORITY_URL}"
      - "traefik.basic.port=4000"
      - "traefik.basic.protocol=http"
      - "traefik.chain.frontend.rule=Host:${CHAIN_URL}"
      - "traefik.chain.port=30333"
      - "traefik.chain.protocol=http"
      - "traefik.chainws.frontend.rule=Host:${CHAIN_WS_URL}"
      - "traefik.chainws.port=9944"
      - "traefik.chainws.protocol=http"
    depends_on:
      - mongodb
    networks:
      - "provotum-server"
    restart: always
  frontend:
    image: ${FRONTEND_IMAGE}
    labels:
      - "traefik.docker.network=files_provotum-server"
      - "traefik.enable=true"
      - "traefik.basic.frontend.rule=Host:${FRONTEND_URL}"
      - "traefik.basic.port=80"
      - "traefik.basic.protocol=http"
    networks:
      - "provotum-server"
    volumes:
      - ./config/Config.js:/usr/share/nginx/html/Config.js
    restart: always

networks:
  provotum-server:
