- name: Copy subkey
  copy:
    src: ../files/subkey
    dest: ./

- name: Set rights to subkey
  file:
    path: ./subkey
    owner: root
    group: root
    mode: '1777'

- name: Generate Aura Keys
  shell: /root/subkey generate --scheme sr25519 > ./aura

- name: Generate Grandpa Keys
  shell: /root/subkey inspect --scheme ed25519 "$(awk 'NR == 2 {print $1}' RS='`' FS='`' ./aura)" > ./grandpa

- name: Copy key.json
  copy:
    src: ../files/key.json
    dest: ./

- name: Remove subkey
  file:
    path: /root/subkey
    state: absent
