version: "3.8"

services:
  sealer:
    container_name: sealer-${SEALER_NUMBER}
    image: ${NODE_IMAGE}
    command: --chain=./customSpec.json --bootnodes ${BOOTNODE} --validator --name sealer-${SEALER_NUMBER} --base-path /tmp/sealer-${SEALER_NUMBER} --port 30333 --ws-port 9944 --rpc-port 9933 --execution Native
    ports:
      - 9933:9933
    volumes:
      - ./customSpec.json:/provotum/customSpec.json

  client:
    container_name: client
    image: ${CLIENT_IMAGE}
    environment:
      - "VA_URL=${VA_URL}"
      - "SEALER_MNEMONIC=${SEALER_MNEMONIC}"

networks:
  default:
    external: true
    name: provotum-server
