version: "3.8"

services:
  # Alice is the Voting Authority
  # Alice doesn't validate any blocks -> just runs a full node
  sealer:
    container_name: sealer-${SEALER_NUMBER}
    image: ${NODE_IMAGE}
    command: --chain=./customSpec.json --bootnodes ${BOOTNODE} --validator --name sealer-${SEALER_NUMBER} --base-path /tmp/sealer-${SEALER_NUMBER} --port 30333 --ws-port 9944 --rpc-port 9933 --execution Native
    network_mode: host
    volumes:
      - ./customSpec.json:/provotum/customSpec.json
