---

- name: Tally Vote
  become: true
  shell:
    cmd: "docker-compose run client ./provotum-cli va tally_question -v {{vote}} -q {{question}}"
  register: out

- debug: var=out.stdout_lines
